"""add_announcement_tagging_fields

Revision ID: 8f426302b3e6
Revises: 1a50d89cf3f6
Create Date: 2026-01-12 21:27:08.088926+05:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f426302b3e6'
down_revision: Union[str, None] = '1a50d89cf3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcements', sa.Column('target_user_ids', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('announcements', sa.Column('target_groups', sa.ARRAY(sa.String()), nullable=True))
    op.create_index(op.f('ix_announcements_target_role'), 'announcements', ['target_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_announcements_target_role'), table_name='announcements')
    op.drop_column('announcements', 'target_groups')
    op.drop_column('announcements', 'target_user_ids')
    # ### end Alembic commands ###
