"""add_events_and_categories

Revision ID: 1a50d89cf3f6
Revises: d6dda6cc309c
Create Date: 2026-01-12 21:11:49.654796+05:30

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a50d89cf3f6'
down_revision: Union[str, None] = 'd6dda6cc309c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('event_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_transactions_event_id'), 'transactions', ['event_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'events', ['event_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_event_id'), table_name='transactions')
    op.drop_column('transactions', 'event_id')
    # ### end Alembic commands ###
